   
name: Terraform static code annalysis  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-build.outputs.build }}
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Terraform security scan
      uses: triat/terraform-security-scan@v3.0.0






