   
name: Terraform static code annalysis  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Terraform security scan
      id: integrationTests
      uses: triat/terraform-security-scan@v3.0.0
    - name: Print scan outcome
      run: |
        echo "Terraform security scan outcome - ${{ steps.integrationTests.outcome }}"
    - name: Print scan failure
      if: steps.integrationTests.outcome == 'failure'
      run: |
        echo "Terraform security scan has failed"
    # - name: Create Pull Request
    #   if: steps.integrationTests.outcome == 'success'
    #   id: cpr
    #   uses: devops-infra/action-pull-request@v0.4.2
    #   with:
    #       github_token: ${{ secrets.token }}
    #       source_branch: terraform_analysis
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.token }}
        commit-message: Add report file
        title: '[Example] Add report file'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: report, automated pr    
    - name: Check outputs
      run: |
        echo "outcome - ${{ steps.cpr.outcome }}"
        echo "output - ${{ steps.cpr.outputs }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"





